### ISSUE TITLE
Can't select Canada in Steam Overlay browser

### ISSUE THREAD

**Issue by nickland** [w4rum/squadlanes#15]
In Mutaha CAF RAAS v1 you cannot select the canadians as a the starting team on the map.
Doesn't work in Firefox either. 
Pretty sure the steam browser uses chromium so I think it's an issue across the board.
Might need more refinement.

**Comment by petevdp** [comment]
Yeah there is some issue with the geometry of the base element for the overlayed buttons. Thanks for taking the time to file an issue - I'll see if I can fix it.

**Comment by w4rum** [comment]
@nickland As a quick workaround for the time being, try zooming in or out or resizing the browser so that the lane display (the small box in the upper middle) is not in line with the point you're trying to click on.

**Comment by w4rum** [comment]
@nickland Should be fixed now. Hit CTRL+F5 if you're still seeing it.

If that doesn't help and the issue persists, feel free to reopen the issue. Thanks for the report!
