### ISSUE TITLE
Fallujah CAF Invasion V1

### ISSUE THREAD

**Issue by BirdieTX** [w4rum/squadlanes#17]
Points went from Asakari Outskirts, to Asakari Slums and then to Shurta Intersection.

**Comment by w4rum** [comment]
Sounds like they updated the layer in 2.7 or 2.8. I'll re-run our extraction scripts when I get on my PC.

**Comment by w4rum** [comment]
Yep, that was it. Re-ran the extraction and your observation checks out.

**Comment by w4rum** [comment]
![image](https://user-images.githubusercontent.com/1405498/122853521-a7061d80-d312-11eb-85e0-68aba6981637.png)
