### ISSUE TITLE
Map select via Link

### ISSUE THREAD

**Issue by mozi-h** [w4rum/squadlanes#18]
Before the major redesign, a map could be selected via the Link like `https://squadlanes.com/#Yehorivka` even after some digging, it doesn't seem to be supported any more?

I'd appreciate it if you could readd this functionality, as I'd like to dynamically present a link to squad lanes in my Discord bot with the relevant current map preselected.

**Comment by w4rum** [comment]
> I'd like to dynamically present a link to squad lanes in my Discord bot with the relevant current map preselected

Oh, nice, it's great to see someone use squadlanes in their own applications!

But yeah, you're right, we didn't think about that feature when we made v2.1 (the new interface). I'll see that we get that back in there.

**Comment by BRMateus2** [comment]
HTTP "?" as the lane parameters may be even easier than using the "#".

**Comment by petevdp** [comment]
> HTTP "?" as the lane parameters may be even easier than using the "#".

We were using query parameters for this previously. I'll see if I can add it back this weekend.

**Comment by Napster653** [comment]
Has this been implemented? I tried with "#" but it doesn't seem to be working.

I link to your page from https://squadmaps.com/ on the detailed view of random layers like this:

![image](https://user-images.githubusercontent.com/32395467/132143544-e90c4431-8e27-42f8-b078-8b9d80e403c5.png)

It'd be cool if I could link directly to a specific layer.

**Comment by w4rum** [comment]
@Napster653 @mozi-h
Sorry for the long turnaround time here but we finally got around to re-implement this.

The syntax should be quite self-explanatory:
```
Kamdesh Highlands, CAF RAAS v1
https://squadlanes.com/#map=Kamdesh+Highlands&layer=CAF+RAAS+v1
```
