### ISSUE TITLE
White screen on Edge v98.0.1108.56

### ISSUE THREAD

**Issue by mozi-h** [w4rum/squadlanes#24]
Opening https://squadlanes.com/ on Edge (tested on multiple instances of the current version 98.0.1108.56) results in a white screen.

The developer console logs the following error
```
src.631cf798.js:1 
        
       Uncaught RangeError: Maximum call stack size exceeded
    at f (src.631cf798.js:1:468)
    at p (src.631cf798.js:1:544)
    at Object.parcelRequire.bMp9.../vue (icon.js:14:1)
    at f (src.631cf798.js:1:468)
    at p (src.631cf798.js:1:544)
    at Object.parcelRequire.eyZ1.../../vue (avatar.js:18:1)
    at f (src.631cf798.js:1:468)
    at p (src.631cf798.js:1:544)
    at Object.parcelRequire.tE4S../avatar (index.js:1:1)
    at f (src.631cf798.js:1:468)
parcelRequire.QPfz @ src.631cf798.js:1
(anonymous) @ src.631cf798.js:1
```

The little research I did on this resulted that it *may* be solved by bumping some dependencies.

**Comment by w4rum** [comment]
Goddammit, Edge.

Not quite sure where the call stack is supposed to overflow but I'll take a look at it when I can.

In the meantime, try using Firefox or Chrome.

**Comment by mozi-h** [comment]
I'm a happy Firefox user myself and was quite surprised to see Edge acting up. This is the first instance of a classic "Internet Explorer Issue" that I've witnessed on Edge. It's usually been behaving surprisingly well ever since it got boosted to Chromium.

**Comment by Tommy-42** [comment]
I don't know if it is related, but I tried opening the site on my Ipad mini ( 5th gen ) on either Safari, Chrome, Firefox but it doesn't work. Empty page that looks like the same issues. 

after little research I am not sure that I can open a dev console on IOS, If I find a way to get an error I will past it here

**Comment by w4rum** [comment]
After 205d324c20574540f49ea62c35b487ff393565b3, the white screen issue seems to be fixed. However, the capture point icons don't show.

I don't see myself having the time to look into that. So for the time being, I'll declare **Edge as unsupported**. Sorry for the inconvenience.
