### ISSUE TITLE
Extraction `extract` task error: `umodel-squadlanes: version GLIBC_2.33 not found`

### ISSUE THREAD

**Issue by mozi-h** [w4rum/squadlanes#25]
When trying to execute `poetry run extract`, the following error is reported:
```
[-] Extracting RAAS data and full-size maps: Failed
[-] -- Extracting Map: Failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mozi_h/squadlanes/extraction/squadlanes_extraction/main.py", line 22, in extract
    extract_map_info.extract()
  File "/home/mozi_h/squadlanes/extraction/squadlanes_extraction/extract_map_info.py", line 466, in extract
    map_data = extract_map(map_dir, progress)
  File "/home/mozi_h/squadlanes/extraction/squadlanes_extraction/extract_map_info.py", line 291, in extract_map
    yaml_content = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./umodel-squadlanes', './intermediate-files/unpacked-assets/Maps/BASRAH_CITY/Gameplay_Layers/Albasrah_RAAS_v1.umap', '-game=ue4.24', '-dump']' returned non-zero exit status 1.
```
Upon manually executing ```./umodel-squadlanes ./intermediate-files/unpacked-assets/Maps/BASRAH_CITY/Gameplay_Layers/Albasrah_RAAS_v1.umap -game=ue4.24 -dump```, the more detailed error ```./umodel-squadlanes: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./umodel-squadlanes)``` is thrown.

System Information: `Kernel: 5.4.0-99-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal`

-----

Sorry, but messing with glib is beyond my know-how and beyond my search engine of choice. Help please.

**Comment by mozi-h** [comment]
It appears the following dependencies were needed (at least on my machine):

- `gcc` to resolve `gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory`
  How it managed to find gcc in the first place, I don't know. :clown_face:
- `libxml2-dev libxslt1-dev zlib1g-dev` some of that to resolve `SDL2/SDL.h: No such file or directory`
- `libsdl2-dev` to resolve `SDL2/SDL.h: No such file or directory`
- `libxtst-dev` to resolve `png.h: No such file or directory`

`poetry run extract` finished successfully

**Comment by w4rum** [comment]
> libxtst-dev

That looks overkill. On Arch, `libxtst` is "X11 Testing -- Resource extension library", which likely pulls in `libpng` as a dependency.

Try looking for a `libpng` for your distro.

**Comment by mozi-h** [comment]
New dependencies:
`gcc`, `g++`, `libsdl2-dev`, `libpng-dev`

**Comment by mozi-h** [comment]
Now, `poetry run tiles` it loops through: `Generating tiles for [...]: Done` and finishes with `Map tiles generated. You now have all the assets necessary to run the website.` as it was successful.
The target directory gets created (if not existing) but stays empty.

**Comment by w4rum** [comment]
> The target directory gets created (if not existing) but stays empty.

The generation process spams stdout quite a bit so most of the logging is suppressed by default. See this part of the readme:

> If any of these steps don't seem to work, e.g., poetry run tiles finishes instantly but doesn't actually produce any tiles, then open the config file, set LOG_LEVEL = "debug" and try again. That should provide you with more verbose output.

**Comment by mozi-h** [comment]
Stale
