### ISSUE TITLE
Failing URL map and lane name normalization and validation

### ISSUE THREAD

**Issue by mozi-h** [w4rum/squadlanes#26]
When a map and / or layer is not valid and case-perfect, the map is not rendered, and the console gets error'd. When the map is invalid, the dropdowns are not rendered.

### Examples
- map wrongly cased: https://squadlanes.com/#map=YehORIvka&layer=RAAS+v1
- lane wrongly cased: https://squadlanes.com/#map=Yehorivka&layer=RaaS+v1
- invalid map name https://squadlanes.com/#map=Yeeeehawrivka&layer=RAAS+v1
- invalid lane name https://squadlanes.com/#map=Yehorivka&layer=RICE+v1

### Proposed fix
[src/LayerSelect.vue#L144](https://github.com/w4rum/squadlanes/blob/0f04c926061604f833457f5512493091c88e587c/src/LayerSelect.vue#L144) and [src/map/index.js#L544](https://github.com/w4rum/squadlanes/blob/0f04c926061604f833457f5512493091c88e587c/src/map/index.js#L544) seem responsible for this issue
- normalization of map and lane names
  - auto-capitalize first letter of `mapName`
  - full-capitalize `layerName` if it contains "raas", first-letter-capitalize otherwise
- `if (!(mapName in raasData))` go to default map, perhaps just redirect to `/` for "autocompletion"
- `if (!(layerName in raasData[mapName]))` go to default lane, perhaps just redirect to `/#map=Mapname` for "autocompletion"

or just poop the user to the default https://squadlanes.com/#map=Narva&layer=RAAS+v1 once shit goes south in `src/map/index.js` at the very least :man_shrugging:

-----

I won't PR this (anytime soon), as getting to know Vue plus your code structure would take a significant amount of time, plus you'd need to fix my mess then anyway.

Also, you have `validateMapName()` and `validateLayerName(map, layer)` in `src/map/index.js`, but aren't using it.

**Comment by mozi-h** [comment]
I agree. OWI is incredibly inconsistent.
As I link to squadlanes via map names, I painfully learnt all the inconsistent naming and the dumb naming of CAF maps.
I'll let the fixing PR close this
Thanks!

**Comment by w4rum** [comment]
> I'll let the fixing PR close this
Oh, I already pushed and deployed my changes. Try to visit the links in your OP.

**Comment by mozi-h** [comment]
Fixed by https://github.com/w4rum/squadlanes/commit/4f17e3d969b7c17dce025295d9951895678738c7
