### ISSUE TITLE
Yehorivka RAAS v5

### ISSUE THREAD

**Issue by yrykxau** [w4rum/squadlanes#27]
Flag point are displaced,its only v5.
Other layers works good
![image](https://user-images.githubusercontent.com/104436304/165299308-1a01b2c7-07e4-4843-a898-af06d80aa5fd.png)

**Comment by w4rum** [comment]
Thanks for the report and sorry for not answering sooner.

While I haven't gotten around to identifying what caused this issue, it appears to be resolved with 09dbb23df133b8b357119649fb432c4a45865288.

Please re-open this issue if you encounter this or a similar issue again.
