### ISSUE TITLE
Goose Bay CAF INV v2 is broken

### ISSUE THREAD

**Issue by BrandonDeaner** [w4rum/squadlanes#29]

**Comment by w4rum** [comment]
Fixed via a955d5e7e0f78227b9d4d0d26c2f6bb34c026984.

Note that this layer no longer exists as of Squad v2.16. I did, however, confirm that the new map logic also works on this outdated layer.

Thank you for the report and sorry for the long turnaround time. This was a massive overhaul of the map UI.

Feel free to re-open this issue or open a new one if you find a similar problem.

**Comment by BrandonDeaner** [comment]
Thanks Tim :)
