### ISSUE TITLE
Black Coast missing

### ISSUE THREAD

**Issue by w4rum** [w4rum/squadlanes#38]
Black Coast doesn't show up in the extracted layer data. Probably an issue with it not being included in the dumped files.

I won't have time until at least the 18th, so don't expect a quick resolution here.

**Comment by IchBinChe** [comment]
Any progress on this issue?

**Comment by w4rum** [comment]
@IchBinChe Not much. I haven't yet spent a lot of time investigating this. I know, however, that the problem is somewhere in the [unpacking](https://github.com/w4rum/squadlanes/blob/master/extraction/squadlanes_extraction/dump_squad_files.py) task, as the Black Coast map files don't even show up in the unpacked assets:
![image](https://user-images.githubusercontent.com/1405498/182713313-39f941d0-137d-4478-bce4-dd4a72f4cf60.png)

**Comment by Svdovych** [comment]
@w4rum I found Black Coast map files in unpacked-assets\Plugins\Expansions\BlackCoast\Content\Maps
Not sure if it's from the main SquadGame\content\Paks dir, because I unpacked every single file from Squad directory before just searching for files with coast in the name. Also I definitely played Squad on that map, so it might have done some initial setup you were talking about

**Comment by w4rum** [comment]
@Svdovych Ah, good catch. I did start Squad before checking again but didn't see any signs of it dynamically loading the map from anywhere. I'd guess that it was there the entire time and I just missed it.

Now I'm having trouble extracting the layer data though. The format for the layer files (`Gameplay_Layers/*.umap`) seems to have changed slightly. I can't figure out how to get the MapTexture position (= the in-game coordinates of the corners of the map image), which I need to display the map image correctly.

Not quite sure how to solve this yet.

**Comment by w4rum** [comment]
Fixed in d9bca7c632fae701a4d4106832872d469d8a87ff

I'll close the issue once I deploy this to the website.
