### ISSUE TITLE
Narva Caps are Broken

### ISSUE THREAD

**Issue by IchBinChe** [w4rum/squadlanes#39]
Caps of Narva RAAS v2 and Narva RAAS v4 are out of order
![Adsız](https://user-images.githubusercontent.com/109835162/180585893-cc5c52f3-ff0d-4af7-9ee6-44189e31d1ed.png)

**Comment by w4rum** [comment]
They're not actually "out of order", but still incorrect. This is related to the warning that's displayed on the website.

With our current (way too permissive) logic, it's possible for Narva paths to go pretty much all over the place.

So Geneva is a possible 5th cap and Church is a possible 4th cap.

We're already working on improving the logic so it's back in line with the ingame data. I think we've made a big breakthrough recently but I still have to implement that. Unfortunately, I'm super short on time the last few days, so don't expect a quick resolution here.

I'll close this issue once we fix the underlying problem.

**Comment by w4rum** [comment]
Fixed in 2325271d0d089cfb77e446e5effcd6f481ec7980
