### ISSUE TITLE
No Faullujah RAAS V1??

### ISSUE THREAD

**Issue by AussieSkull** [w4rum/squadlanes#4]
Hi Guys, notice that Fallujah RAAS v1 is missing from the list. US vs MEA

**Comment by w4rum** [comment]
Unfortunately, this will probably not be fixed too son. Fallujah RAAS v1 is using a different kind of RAAS mechanic (parallel AAS) in which some clusters can have multiple active capture points. You might have seen this in-game before when three or four flags were active at the same time.

Our algorithm for predicting RAAS lanes does not support parallel AAS at the moment and we're not sure how we can make it support that.

Fallujah RAAS v1 might be added as soon as we finish our "lane viewing" mode that allows simply viewing the lanes, without the interactive lane prediction functionality.

**Comment by w4rum** [comment]
I've included Fallujah in the newest dataset. Just note that it doesn't have PAAS support. So all you can do is see which capture points exist.
