### ISSUE TITLE
Grey Screen On Latest Google Chrome, Brave & Edge

### ISSUE THREAD

**Issue by TempusOwl** [w4rum/squadlanes#40]
I created a new issue due to it being a breaking issue on multiple browsers, but this issue is related https://github.com/w4rum/squadlanes/issues/24 it appears and is not limited just to edge anymore. I just updated chrome to ver 104.0.5112.81 (Official Build) (64-bit) and this appears to break the website with the following console error. The issue seems specific to browsers using the latest Chromium version. I mainly use brave, and this issue is present there too.

`Uncaught RangeError: Maximum call stack size exceeded
    at f (src.99b48d1e.js:1:468)
    at p (src.99b48d1e.js:1:544)
    at parcelRequire.bMp9.../vue (icon.js:14:1)
    at f (src.99b48d1e.js:1:468)
    at p (src.99b48d1e.js:1:544)
    at parcelRequire.eyZ1.../../vue (avatar.js:18:1)
    at f (src.99b48d1e.js:1:468)
    at p (src.99b48d1e.js:1:544)
    at parcelRequire.tE4S../avatar (index.js:1:1)
    at f (src.99b48d1e.js:1:468)`
The only workaround is to use Firefox.

**Comment by w4rum** [comment]
Thank you for reporting this. I'll bump it up in my priorities since Chrome is probably somewhere close to 50% of the user base. I'll have to see if I can cram it in in the next few days.

**Comment by w4rum** [comment]
Interestingly, I can't reproduce this with either
- `Google Chrome 104.0.5112.79` (Linux) or
- `Google Chrome 106.0.5216.6 dev` (Linux) or
- `Google Chrome 106.0.5216.6` (Windows)

It only appears on the current stable version on Windows (`104.0.5112.81`). As with the other related issues, this is probably caused by the bundler `parcel`. I'll look into that.

**Comment by TempusOwl** [comment]
Just to confirm, I am seeing what you are seeing on my system too, I downloaded chrome canary https://www.google.com/chrome/canary/ (for those who want another workaround) and issue is fixed for v106.0.5225.0.

**Comment by z1haze** [comment]
it is definitely an issue.. We have a member from the EU who does not have this issue with chrome though. Everyone i know in the US it is broken in chrome.

**Comment by Move2win** [comment]
Same issue here

Windows 10 with Chrome 104.0.5112.81

**Comment by Ech0riginal** [comment]
@w4run I also cannot reproduce the errors on linux via `google-chrome-dev-106.0.5216.6-1` and `firefox 103.0.1-1`.

**Comment by w4rum** [comment]
Fixed for at least Chrome in 205d324c20574540f49ea62c35b487ff393565b3.

@TempusOwl can you check in Brave?

**Comment by TempusOwl** [comment]
It is working great now. I tested it on:
Edge: 104.0.1293.47
Brave: v1.42.88 (104.0.5112.81)
Chrome Canary (106.0.5232.0)

**Comment by z1haze** [comment]
Working in Windows 10 Chrome Version 104.0.5112.81 (Official Build) (64-bit)

**Comment by w4rum** [comment]
Perfect, thanks for the feedback.
