### ISSUE TITLE
Haru RAASv5 issue

### ISSUE THREAD

**Issue by marchwicki** [w4rum/squadlanes#45]
Haru RAAS v5 points. 

RAAS v5 can go Missile SIlos Underground and then straight to Water Treatment as the second point.

https://imgur.com/a/jCwdrgg

**Comment by w4rum** [comment]
Thanks a lot for the ingame screenshot! I'll look into that.

I've already noticed that Harju has a few caps out-of-position, sometimes even off the map entirely. Something seems to be different with Harju regarding the Unreal assets it's using. I'll have to reverse engineer a bit more here and adapt the data mining scripts.

**Comment by w4rum** [comment]
@marchwicki Are you sure this is v5 and not v3 or v4? My data has way fewer points for v5. `Ammunition Bunker` and `Airfield Power Plant` aren't even there.

**Comment by w4rum** [comment]
The position of the mains lines up with v3 and v4, not v5. And the website already supports
`West Main -> Missile Silos Underground -> Water Treatment`

so I'm assuming you mixed up the layers.

If you're sure you were on v5 and not v3 or v4 and the error is indeed on my end, feel free to re-open the issue.
