### ISSUE TITLE
Unpacking Game Files

### ISSUE THREAD

**Issue by mrpatricko** [w4rum/squadlanes#48]
Please forgive me for opening an issue to ask a question. 

How does one unpack the game files? I have _some_ experience with Vue.js and would like to recreate Squadlanes to better understand your code and possibly contribute in the future.

Do you download the SDK to a Linux machine and use those game files for unpacking? Do you use a Windows machine at any point in unpacking the map layer data and map images?

Thank you,
Patrick

**Comment by w4rum** [comment]
Hey Patrick,

generally, the process of acquiring the extracted layer information is described in the readme.

Regarding your question specifically, I'm not sure what you mean by "unpack". If you mean the entire extraction process, please refer to the readme.

In this project, I use the term "unpack" to refer to the **first step of the extraction**, i.e., the process of unpacking the PAK files to a directory tree containing all of the "cooked" Unreal assets.

This first step is not based on the SDK at all. Instead, I download the regular Windows game via Steam onto my Windows machine. Then, I run my first extraction script (`dump_squad_files.py`) on my Linux machine, with the Windows drive mounted in.

*Side note: This project isn't very heavily based on Linux. There is a somewhat-stale PR-in-development that is concerned with porting this project to Windows. However, I personally haven't found the time to help with that.*

That python script uses `UnrealPakTool` (included in `extraction/UnrealPakTool`) and the decryption key included in `extraction/squadlanes_extraction/config.py` to unpack the PAK files of the regular game distribution.

Those unpacked files are then used in the **second step of the extraction**, which is implemented in `extract_map_info.py`.
That script

1. uses my `UEViewer` fork to inspect the game layer `.umap` files and dump the information about capture points, clusters, and lanes to an intermediate (and very ugly and undocumented) YAML format
2. processes the intermediate format to a usable all-in-one layer info file (`raas-data.yaml`).

The `raas-data.yaml` file is the core product of the extraction script.

There is also a **third part of the extraction**, implemented in `generate_map_tiles.py`, which takes the original, full-size map background images from the first step, and produces more web-friendly tiled versions of it. The front-end map library `leaflet.js` uses those tiled images to display the map, so without this third step, you won't have any background images.

Feel free to follow up if you have any specific questions.

\- Tim

**Comment by mrpatricko** [comment]
This is FANTASTIC information! I'd gone over the README file a few times but was never sure which parts were on Windows and/or Linux.

Thank you so much for pointing me in the right direction!
