### ISSUE TITLE
Harju RAASv3 Flags

### ISSUE THREAD

**Issue by co-devs** [w4rum/squadlanes#49]
Harju RAAS v3 points.

RAAS v3 can go Shopping District as point 5 after BioChem lab and before Lumber Yard

![image](https://user-images.githubusercontent.com/3297661/225138514-ca65d113-3b72-4232-8ea1-39972a44fb6a.png)

**Comment by co-devs** [comment]
It looks like the point may already be labelled, but as a second Town Hall rather than Shopping District

**Comment by w4rum** [comment]
It appears this issue was present in game at version 4.0. I just updated squadlanes from 4.0 to 4.3.1 and the point is now correctly labelled.
