### ISSUE TITLE
mobile UI ?

### ISSUE THREAD

**Issue by fjod** [w4rum/squadlanes#5]
When I open squadlanes.com on mobile, I can see only map (default is Narva RAAS V1) and no buttons to change it. On PC there are buttons on the right side; on mobile there is nothing. Please update mobile UI, it's very useful to play Squad and use mobile for mortar calculator / lanes.

**Comment by w4rum** [comment]
Yep, this is definitely on our To-Do list. The incompatibility with smaller screens / portrait mode is one of my bigger gripes with our current UI. I personally don't have that problem as I just open squadlanes on a second monitor but I can definitely see mobile screens as a use-case.

**Comment by w4rum** [comment]
Is implemented by #10 and will be sent to the live website once we get release 2.1 done.
