### ISSUE TITLE
Map selector cuts off last options on mobile

### ISSUE THREAD

**Issue by robinstauntoncollins** [w4rum/squadlanes#51]
Can just barely see Talill outskirts and can't see Yeho when selecting map on Firefox browser on mobile.
![SmartSelect_20230711-083002_Firefox](https://github.com/w4rum/squadlanes/assets/25299948/2b6c19f2-7e76-4bc8-beab-8d752f444f84)

It's even worse on Chrome. Can't select anything lower than Sumari.

Selecting Desktop Site in browser options is a workaround.

**Comment by petevdp** [comment]
thanks - fixed this here https://github.com/w4rum/squadlanes/pull/52

**Comment by w4rum** [comment]
Deployed to https://squadlanes.com/#map=Narva&layer=RAAS+v1
