### ISSUE TITLE
Black Coast RAASv1

### ISSUE THREAD

**Issue by cafoggy** [w4rum/squadlanes#55]
I'm pretty sure that pathing from Team 2 isn't correct in the following scenario:

Derevnya -> Old Baracks doesn't lead to Quarry all the time. I just played a game where the path went Derevnya -> Old Baracks -> Chernikov Electric

![2023-09-10 19_34_18-Window](https://github.com/w4rum/squadlanes/assets/21335682/e9df981e-6e15-425b-9cf7-9ec73635ef1b)

**Comment by w4rum** [comment]
@cafoggy You don't happen to have a screenshot of your game, do you?

Not trying to wipe this away but I've had cases where people selected a wrong, but very similar layer.

Just to make sure, which layer do you have selected on Squadlanes in that screenshot?

**Comment by w4rum** [comment]
> Just to make sure, which layer do you have selected on Squadlanes in that screenshot?

Scratch that. You've already written that in the title. I'm just blind.

**Comment by cafoggy** [comment]
Unfortunately I didn't take a screenshot. It's certainly possible that I
wasn't in fact playing on RAASv1 but I called out Quarry as the next flag
during the game and I was a quiet surprised when Chernikov came up and
rechecked which layer I was on.

**Comment by w4rum** [comment]
Closing due to staleness
