### ISSUE TITLE
Favicon change?

### ISSUE THREAD

**Issue by D4n2021** [w4rum/squadlanes#58]
Hi, did the favicon change, or did squadmaps.com simply copy our favicon without our approval? Both are the same currently, and this is very confusing obviously, when using the "pinning" feature in todays' webbrowsers.
(here are both websites pinned next to each other)

![grafik](https://github.com/w4rum/squadlanes/assets/20766261/84933393-8c89-42f0-a517-54c28521709a)

**Comment by D4n2021** [comment]
also see https://github.com/w4rum/squadlanes/pull/59

**Comment by w4rum** [comment]
I'm not sure where exactly the favicon first came from. @mozi-h added that about two years ago in 47cd3408f9e8bd221d2770de19e9a20dbc7527ca.

I heavily collaborated with the current developer of SquadMaps and shared what I've learned about RAAS and Squad data mining with their side, including giving them our RAAS data and debugging some problems with their implementation of the RAAS prediction algorithm.

I don't really care whether they copied our favicon as well.

I also do not really see the point in us changing our favicon either, to be honest. I like the current one. There is little reason to use both websites at once. And given that Squadmaps is more feature-rich and I'm not planning on adding new features to Squadlanes (I don't play Squad anymore), I expect Squadlanes to become somewhat obsolete in the long run anyway.

**Comment by D4n2021** [comment]
Okay!
