### ISSUE TITLE
v2 map images not loading right

### ISSUE THREAD

**Issue by Metroseksuaali** [w4rum/squadlanes#8]
Hey, 

Using chrome on windows pc. 

Tried to refresh cache and delete history.

I can see cap "balls" on the map but maps are not rendering right. Sometimes i see it when zoomed all the way out but after couple seconds it turns back to black.

Some of them work fine.

Ones that have problems are:

* Fallujah 
* Kokan Valley
* Lashkar valley
* Logar Valley
* Manic 5
* Mestia 

Others are working like normal to me.

**Comment by w4rum** [comment]
Can confirm. Seems like the adjustments I made for extracting minimap file names didn't quite work out. I'll get on it. Thanks for the extensive report!

**Comment by w4rum** [comment]
It wasn't about the names after all. When going to V2, I reduced the amount of unnecessary files that I extract from the game data and it looks like I killed some of the minimaps in that process. I fixed the extraction scripts and uploaded the correct minimaps. Should be fixed now.

Feel free to comment if this issue pops back up.
